version: '3.4'

services:
  catalog.api:
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    expose:
      - 5000
    depends_on:
      - postgres
  reverse.proxy:
      image: nginx:latest
      ports:
          - "80:4000"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - catalog.api
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432