version: '3.4'

services:
  catalog.api:
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    expose:
      - 5000
  reverse.proxy:
      image: nginx:latest
      ports:
          - "80:4000"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - catalog.api
